package com.yotto.basketball.entity;

public enum AuditEventType {
    REGISTERED,
    EMAIL_VERIFIED,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    LOCKED_AUTO,
    LOCKED_ADMIN,
    UNLOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    EMAIL_CHANGE_REQUESTED,
    EMAIL_CHANGED,
    ROLE_CHANGED,
    ACCOUNT_DELETED,
    RATE_LIMITED,
    EMAIL_SEND_FAILED,
    BROADCAST_SENT
}
