package com.yotto.basketball.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * A gazetteer alias mapping a text phrase to a team OR a conference (exactly
 * one is set, enforced by a DB CHECK). AUTO rows are regenerated by reseeding
 * and never overwrite MANUAL/BLOCK rows; BLOCK rows suppress an alias for a
 * target entirely. Ambiguous aliases only tag when corroborated
 * (docs/NEWS_MODULE.md §5.7).
 */
@Entity
@Table(name = "news_aliases")
public class NewsAlias {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    private String alias;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "team_id")
    private Team team;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "conference_id")
    private Conference conference;

    @NotNull
    @Enumerated(EnumType.STRING)
    private Kind kind = Kind.AUTO;

    @NotNull
    private Boolean ambiguous = false;

    @NotNull
    @Column(name = "case_sensitive")
    private Boolean caseSensitive = false;

    @NotNull
    private Boolean enabled = true;

    @Column(name = "created_by")
    private String createdBy;

    @NotNull
    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();

    public enum Kind {
        AUTO,
        MANUAL,
        BLOCK
    }

    public NewsAlias() {
    }

    public static NewsAlias forTeam(String alias, Team team, Kind kind, boolean ambiguous, boolean caseSensitive) {
        NewsAlias a = new NewsAlias();
        a.alias = alias;
        a.team = team;
        a.kind = kind;
        a.ambiguous = ambiguous;
        a.caseSensitive = caseSensitive;
        return a;
    }

    public static NewsAlias forConference(String alias, Conference conference, Kind kind,
                                          boolean ambiguous, boolean caseSensitive) {
        NewsAlias a = new NewsAlias();
        a.alias = alias;
        a.conference = conference;
        a.kind = kind;
        a.ambiguous = ambiguous;
        a.caseSensitive = caseSensitive;
        return a;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Team getTeam() {
        return team;
    }

    public void setTeam(Team team) {
        this.team = team;
    }

    public Conference getConference() {
        return conference;
    }

    public void setConference(Conference conference) {
        this.conference = conference;
    }

    public Kind getKind() {
        return kind;
    }

    public void setKind(Kind kind) {
        this.kind = kind;
    }

    public Boolean getAmbiguous() {
        return ambiguous;
    }

    public void setAmbiguous(Boolean ambiguous) {
        this.ambiguous = ambiguous;
    }

    public Boolean getCaseSensitive() {
        return caseSensitive;
    }

    public void setCaseSensitive(Boolean caseSensitive) {
        this.caseSensitive = caseSensitive;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NewsAlias that = (NewsAlias) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "NewsAlias{id=" + id + ", alias='" + alias + "', kind=" + kind + "}";
    }
}
